### PR TITLE
Add check for extended attribute files in validator.

### PR DESCRIPTION
**Pull request by riga**
Hi!

This small PR fixes an issue that seems like an edge case at first, but should appear regularly for people creating submission files and archives with `tar` on MacOS.

## Issue

Macs with HSF+ volumes (default) add extended attributes to files every time they are opened, changed, etc. (denoted by `@` at the end of the permission bits in `ls -l`). When creating submission archives with BSD-style tar (default on Mac), per file with these attributes a second file named `._<actual_name>` is added as well. This causes the `FullSubmissionValidator` to raise errors in

https://github.com/HEPData/hepdata-validator/blob/7ccfa8da8189e5d5f2bbf50ab434f919e25f9efc/hepdata_validator/full_submission_validator.py#L207-L213

à la

```
ERROR: submission.tgz is invalid.
	 submission.yaml is valid HEPData submission YAML.
	 table_2.yaml is valid HEPData data YAML.
       	 figure_4_3.yaml is valid HEPData data YAML.
	 error - ._figure_4_3.yaml is not referenced in the submission.
```

It took me a while to get to the root of the problem (mainly because BSD tar on MacOS gets rid of these files when unpacking) and I think it would be safe to skip these extra files.

## Fix

I added a helper function to `FullSubmissionValidator.validate` that checks if a shipped file is indeed the result of `tar` (and possibly other archiving tools) handling files with extended attributes.

There are also two possible workarounds on the user side but I think it would be more convenient to just skip these cases. I'm still listing them here for completeness and people observing similar issues.
- `brew install gnu-tar` and running `gtar` instead of `tar`.
- `xattr -c *.yaml` to remove all attributes from submission files before running `tar`. This has to be repeated every time after a file was opened again.

### CODE REVIEW

**Comment by GraemeWatt** [comment]
Many thanks for the PR, @riga.  Indeed, I had this problem myself recently and it seems to be a common issue for HEPData uploaders.  In my case, I gave up using `tar` to create my archive file and switched to `zip` instead, which does not have this problem.  However, I'm reluctant to make the validator accept these extra files, which HEPData will store on disk but never use.  One purpose of introducing the check for extra files was to avoid storing system-specific hidden files.  From a Google search, I found [a solution](https://superuser.com/a/260264) that involves setting an environment variable `COPYFILE_DISABLE=1` before running `tar`.  I've checked that solution works for me on my laptop (macOS 11.4).  Could you please check if it works for you too?  If so, we could maybe modify the validator error message for extra files starting with `._` to give a hint to the user about `COPYFILE_DISABLE` if they are using macOS with `tar`.  What do you think?

**Comment by riga** [comment]
Hi @GraemeWatt ,

I can confirm that setting `COPYFILE_DISABLE=1` works for me.

Showing a hint in the error message is also ok for me and I added another commit for that 👍
Also, I made this message a "hint" in the second commit. I can revert it in case this warning should still use the "error" level.

**Comment by GraemeWatt** [comment]
This is great.  I think a "hint" is fine.  I tested your branch and it works well.  Could you please add a minimal test to cover the newly added lines?  Running `pytest testsuite` on your branch gives:
```
Name                                             Stmts   Miss  Cover   Missing
------------------------------------------------------------------------------
hepdata_validator/full_submission_validator.py     241      4    98%   220-222, 231
```
We're trying to keep 100% test coverage for this repository.  While running the tests on a new laptop (macOS), I found that they need PyYAML to be built with the LibYAML C bindings.  I've opened a new issue #45 to make the tests pass also with pure-Python PyYAML.

**Comment by GraemeWatt** [comment]
Thanks for adding the tests.  I'll merge now.  I might wait until the other 2 open issues on this repo are addressed before making a new release of the validator package that can be deployed on [hepdata.net](https://hepdata.net).  Many thanks for your contribution!

**Comment by GraemeWatt** [comment]
The latest `hepdata-validator` v0.3.3 has now been released and deployed on [hepdata.net](https://www.hepdata.net).  Sorry for the delay and thanks again for your contribution, @riga.

**Pull request merged**
