### PR TITLE
Remote schemas validation

### PR DESCRIPTION
**Pull request by Sinclert**
This PR aims to **partially** tackle https://github.com/HEPData/hepdata/issues/164, as the `hepdata` validator needs to support _"remotely defined_" schemas in order to allow submissions containing data files from other organizations / companies.

**Decisions taken:**
- Remote schemas will be organized by `company`/`project`/`version`.
- They will be stored separately from the native HEP schemas.

**Clarifications:**
- I have mocked tests in order for them not to depend on an external `https://...` resource.
- I have updated the docs for supporting the `HTTPSchemasDownloader` new entity.

### CODE REVIEW

**Comment by Sinclert** [comment]
I have updated this PR:

- Substituting the previously named `company` attribute by `org`.
- Defining a new private method called `parse_remote_url`, that parses the initialization schemas URL and checks for its correctness.

**Comment by Sinclert** [comment]
I have updated this PR:
- Adding a new `get_schema_type` method to build a valid `type` value to be passed to the `DataFileValidator`.

**Comment by kratsg** [comment]
./cc @lukasheinrich @matthewfeickert

**Comment by Sinclert** [comment]
I have updated this PR by adding a real world `pyhf` test (the file is around 19.000 lines long).

I would say it is now **ready for review**. If the test file is considered too long, we can prune it as desired 😄

**Pull request merged**
